Add netio feature
Thunder-cut-2020/WhiteBoard-Client pull request #32
Opened 2020-02-13 05:39 UTC by pllapallpal

Send image of canvas to the server
Display image received from the server to participantsPanel
Set the type of the data to send to the server
Determine the type of data received from the server

2020-02-13 06:01 UTC, sjy5386 commented on src/com/thunder_cut/netio/Connection.java
> +            connectionModule.socketChannel.connect(new InetSocketAddress("127.0.0.1", 3001));
Do not hard coding host address and port number.

2020-02-13 06:07 UTC, Kasania requested changes

2020-02-13 06:07 UTC, Kasania commented on src/com/thunder_cut/graphics/controller/DrawingModeHandler.java
> -        drawingFeatures.get(selectedDrawingMode).process(mouseData, canvasPixelInfo, color);
Remove comment

2020-02-13 06:07 UTC, Kasania commented on src/com/thunder_cut/netio/Connection.java
> +     * - mouseReleased() method, which is in constructor of DrawingCanvas class
Mismatch comment with where it called

2020-02-13 06:07 UTC, Kasania commented on src/com/thunder_cut/netio/Connection.java
> + * ConnectionModule is a class that supervises net i/o.
Mismatch comment with Class name

2020-02-13 06:07 UTC, Kasania commented on src/com/thunder_cut/netio/Connection.java
> +     * object ConnectionModule should be created in <code>main</code>
Mismatch comment with class name

2020-02-13 06:07 UTC, Kasania commented on src/com/thunder_cut/netio/Connection.java
> +     * object ConnectionModule should be created in <code>main</code>
Mismatch comment with behavior

2020-02-13 06:07 UTC, Kasania commented on src/com/thunder_cut/netio/DataReceiver.java
> + * ParticipantsImageReceiver.java
Mismatch comment with Class name

2020-02-13 06:07 UTC, Kasania commented on src/com/thunder_cut/netio/DataReceiver.java
> +//        dataType.put(DataType.MSG, ***);
Remove comment

2020-02-13 06:07 UTC, Kasania commented on src/com/thunder_cut/netio/DataReceiver.java
> +            Map<HeaderItem, Integer> header = readHeader();
You don't use Map instance. put readHeader() into readData()    
readData(readHeader));

2020-02-13 06:07 UTC, Kasania commented on src/com/thunder_cut/netio/DataUnwrapper.java
> + * ReceivedData.java
Mismatch comment with class name

2020-02-13 06:07 UTC, Kasania commented on src/com/thunder_cut/netio/DataWrapper.java
> + * SentData.java
Mismatch comment with class name

2020-02-13 06:07 UTC, Kasania commented on src/com/thunder_cut/netio/Connection.java
> + * ConnectionModule.java
Mismatch comment with class name

2020-02-13 10:41 UTC, Kasania commented
Need rewriting comments.
Comments have to be clearly, simply and readably.

2020-02-16 13:30 UTC, Kasania requested changes

2020-02-16 13:30 UTC, Kasania commented on src/com/thunder_cut/netio/DataReceiver.java
> +            dataType.get(decapsulatedData.dataType).accept(decapsulatedData.srcID, decapsulatedData.data.array());
This will cause an bug.    
Use thread-safe data structure.    
or remove data structure, and use if expression.

2020-02-16 13:30 UTC, Kasania commented on src/com/thunder_cut/netio/DataReceiver.java
> +    private Map<Character, BiConsumer<Integer, byte[]>> dataType;
Name is confusing. please rename this.

2020-02-16 15:14 UTC, Kasania approved these changes

2020-02-16 15:14 UTC, merged